"""add income column in vendors

Revision ID: 0b8ab4ba7676
Revises: af96fc899225
Create Date: 2025-09-27 19:07:10.253326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b8ab4ba7676'
down_revision: Union[str, Sequence[str], None] = 'af96fc899225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('income', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'income')
    # ### end Alembic commands ###
