"""add inventory column to product

Revision ID: 8af56a2eb23b
Revises: ed57e763778e
Create Date: 2025-09-23 16:10:33.573918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8af56a2eb23b'
down_revision: Union[str, Sequence[str], None] = 'ed57e763778e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('inventory', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'inventory')
    # ### end Alembic commands ###
