"""add profile image column in vendors

Revision ID: af96fc899225
Revises: 8af56a2eb23b
Create Date: 2025-09-25 17:17:17.693155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af96fc899225'
down_revision: Union[str, Sequence[str], None] = '8af56a2eb23b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('profile_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'profile_image')
    # ### end Alembic commands ###
