"""add is_avtive column to products table

Revision ID: ed57e763778e
Revises: ed80eb09c3b9
Create Date: 2025-09-21 17:31:29.320686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed57e763778e'
down_revision: Union[str, Sequence[str], None] = 'ed80eb09c3b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'is_active')
    # ### end Alembic commands ###
