"""add rate column in vendors and product table

Revision ID: ed80eb09c3b9
Revises: 11272f0c4c92
Create Date: 2025-09-21 13:36:16.114609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed80eb09c3b9'
down_revision: Union[str, Sequence[str], None] = '11272f0c4c92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('rate', sa.Float(), nullable=True))
    op.add_column('product', sa.Column('buy_freq', sa.Integer(), nullable=True))
    op.add_column('vendors', sa.Column('rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'rate')
    op.drop_column('product', 'buy_freq')
    op.drop_column('product', 'rate')
    # ### end Alembic commands ###
